services:
  flutter:
    build:
      context: .
    container_name: flutter-dev
    working_dir: /app
    volumes:
      - .:/app
      - flutter-cache:/root/.pub-cache
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - DISPLAY=${DISPLAY}
    ports:
      - "5037:5037" # for adb preview
      - "8000:8000" # for web preview
    stdin_open: true
    tty: true

volumes:
  flutter-cache:
