services:
  flutter:
    build:
      context: .
      args:
        FLUTTER_VERSION: ${FLUTTER_VERSION:-3.29.0}
        ANDROID_PLATFORM_VERSION: ${ANDROID_PLATFORM_VERSION:-33}
        ANDROID_BUILD_TOOLS_VERSION: ${ANDROID_BUILD_TOOLS_VERSION:-33.0.2}
    container_name: flutter-dev
    working_dir: /app
    volumes:
      - .:/app
      - flutter-cache:/root/.pub-cache
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - DISPLAY=${DISPLAY}
    ports:
      - "5037:5037" # for adb preview
      - "8000:8000" # for web preview
    stdin_open: true
    tty: true

volumes:
  flutter-cache:
